server:
  port: 8032
spring:
  datasource:
    username: root
    password: root
    url: jdbc:mysql://127.0.0.1:3306/logisticsmanage?characterEncoding=utf8&useSSL=false&serverTimezone=UTC&rewriteBatchedStatements=true
    driver-class-name: com.mysql.cj.jdbc.Driver
#  web:
#    resources:
#      static-locations: classpath:static/,file:SystemData
mybatis-plus:
  mapper-locations: classpath:/mapper/*.xml
  type-aliases-package: com.ming.logistics.pojo
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl






